server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ssm_db
    username: root
    password: '123456'
    type: com.alibaba.druid.pool.DruidDataSource
  devtools:
    restart:
      exclude: static

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info
    ebank: debug
  group:
    ebank: com.controller
  file:
    name: server.log
  logback:
    rollingpolicy:
      max-file-size: 4KB
      file-name-pattern: server-%d{yyyy-MM-dd}-%i.log

jetcache:
  statIntervalMinutes: 1
  remote:
    default:
      keyConvertor: fastjson
      valueEncode: java
      valueDecode: java
      type: redis
      host: 124.221.192.10
      port: 6379
      password: 123456
      poolConfig:
        maxTotal: 50
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
